Emlak Sitesi 1/Controllers/ilanController.cs
using Emlak_Sitesi_1.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Emlak_Sitesi_1.Controllers
{
    public class ilanController : Controller
    {
        EmlakEntities1 db = new EmlakEntities1();
        // GET: ilan
        public ActionResult Index()
        {
            return View();
        }

        // GET: ilan/Details/5
        public ActionResult Details(int id)
        {          
            var ilanList = db.ilans.Where(i => i.ilanID == id).ToList();
            ViewBag.details = ilanList;
            return View();
        }

        // GET: ilan/Create
        public ActionResult Create()
        {
            ViewBag.kategoriID = new SelectList(db.kategoris, "kategoriID", "kategoriAd");
            ViewBag.islemID = new SelectList(db.islems, "islemID", "islemAd");
            return View();
        }

        // POST: ilan/Create
        [HttpPost]
        public ActionResult Create(ilan ilan)
        {
            try
            {
                string kullaniciAdi = Session["username"].ToString();

                var kullanici = db.kullanicis.Where(i => i.kullaniciAdSoyad == kullaniciAdi).SingleOrDefault();
                ilan.kullaniciID = kullanici.kullaniciID;
                db.ilans.Add(ilan);
                db.SaveChanges();

                return RedirectToAction("Index","Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: ilan/Edit/5
        public ActionResult Edit(int id)
        {
            var ilanım = db.ilans.Where(i => i.ilanID == id).SingleOrDefault();
            ViewBag.kategoriID = new SelectList(db.kategoris, "kategoriID", "kategoriAd");
            ViewBag.islemID = new SelectList(db.islems, "islemID", "islemAd");
            return View(ilanım);
        }

        // POST: ilan/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ilan ilan)
        {
            try
            {
                var ilanım = db.ilans.Where(i => i.ilanID == id).SingleOrDefault();
                ilanım.ilanAciklama = ilan.ilanAciklama;
                ilanım.ilanAdres = ilan.ilanAdres;
                ilanım.ilanBaslik = ilan.ilanBaslik;
                ilanım.ilanBinaEsyaliMi = ilan.ilanBinaEsyaliMi;
                ilanım.ilanBinaisitma = ilan.ilanBinaisitma;
                ilanım.ilanBinaKacinciKat = ilan.ilanBinaKacinciKat;
                ilanım.ilanBinaKat = ilan.ilanBinaKat;
                ilanım.ilanBinaYasi = ilan.ilanBinaYasi;
                ilanım.ilanFiyat = ilan.ilanFiyat;
                ilanım.ilanOdaSayisi = ilan.ilanOdaSayisi;
               
                ilanım.islemID = ilan.islemID;
                ilanım.kategoriID = ilan.kategoriID;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        // GET: ilan/Delete/5
        public ActionResult Delete(int id)
        {
            var sil = db.ilans.Where(i => i.ilanID == id).SingleOrDefault();

            return View(sil);
        }

        // POST: ilan/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, ilan ilan)
        {
            
            try
            {
                var sil = db.ilans.Where(i => i.ilanID == id).SingleOrDefault();
                db.ilans.Remove(sil);
                db.SaveChanges();
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult List()
        {
            string kullaniciAd = Session["username"].ToString();
            var ilanList = db.kullanicis.Where(i => i.kullaniciAdSoyad == kullaniciAd).SingleOrDefault().ilans.ToList();
          
            return View(ilanList);

        }
    }
}

Emlak Sitesi 1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Emlak Sitesi</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/_references.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.intellisense.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/respond.js"></script>
    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/kullaniciDetay.js"></script>
    <link href="~/Content/kullaniciDetay.css" rel="stylesheet" />
</head>
<body>
    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Emlak Sitesi", "Index", "Home" , new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("AnaSayfa", "Index", "Home")</li>
                   
                </ul>
                @{ 
                    if (Session["username"] == null)
                    {
                        <ul class="nav navbar-nav right glyphicon-arrow-right">
                            <li>@Html.ActionLink("Giriş Yap", "Login", "Kullanici")</li>
                            <li>@Html.ActionLink("Kayıt Ol", "Create", "Kullanici")</li>

                        </ul>
                            }

                    else if (Session["username"]!=null)
                            {
                        <ul class="nav navbar-nav right glyphicon-arrow-right">
                            <li>@Html.ActionLink("İlan Ekle", "Create", "ilan")</li>
                            <li>@Html.ActionLink("İlan Listele", "List", "ilan")</li>
                            <li>@Html.ActionLink(Session["username"].ToString(), "Profils" , "Kullanici")</li>                         
                            <li>@Html.ActionLink("Çıkış Yap", "LoginOut", "Kullanici")</li>
                        </ul>
                    }
                }          
            </div>           
        </div>
    </div>

    <div class="container body-content">

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ömer Açık</p>
        </footer>
    </div>

   
  
    @RenderSection("scripts", required: false)
</body>
</html>